# Generated by Django 6.0.6 on 2026-08-14 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenApi',
            fields=[
                ('id_token', models.BigAutoField(db_column='id_token', primary_key=True, serialize=False)),
                ('aplicacion', models.CharField(blank=True, db_column='aplicacion', max_length=100, verbose_name='Aplicacion que lo solicito')),
                ('prefijo', models.CharField(db_column='prefijo', help_text='Primeros caracteres, para reconocerlo en este listado.', max_length=12, verbose_name='Inicio del token')),
                ('huella', models.CharField(db_column='huella', max_length=64, unique=True, verbose_name='Huella SHA-256')),
                ('creado', models.DateTimeField(auto_now_add=True, db_column='creado', verbose_name='Fecha de creacion')),
                ('expira', models.DateTimeField(blank=True, db_column='expira', help_text='Vacio = no caduca.', null=True, verbose_name='Caduca el')),
                ('ultimo_uso', models.DateTimeField(blank=True, db_column='ultimo_uso', null=True, verbose_name='Ultimo uso')),
                ('revocado', models.BooleanField(db_column='revocado', default=False, verbose_name='Revocado')),
                ('ip_origen', models.GenericIPAddressField(blank=True, db_column='ip_origen', null=True, verbose_name='IP desde la que se pidio')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_api', to=settings.AUTH_USER_MODEL, verbose_name='Dueno del token')),
            ],
            options={
                'verbose_name': 'Token de API',
                'verbose_name_plural': 'Tokens de API',
                'db_table': 'token_api',
                'ordering': ['-creado'],
            },
        ),
    ]
