# Generated by Django 6.0.6 on 2026-08-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenapi',
            name='permisos',
            field=models.JSONField(blank=True, db_column='permisos', default=dict, help_text='{recurso: [acciones]} tal como estaban al crearlo.', verbose_name='Permisos con los que se emitio'),
        ),
        migrations.AddField(
            model_name='tokenapi',
            name='rol',
            field=models.CharField(blank=True, db_column='rol', help_text='SUPERADMIN, ADMIN, PROFESOR o ESTUDIANTE en el momento de la emision. El rol vigente se recalcula en cada peticion; este campo es el registro de como nacio.', max_length=15, verbose_name='Rol con el que se emitio'),
        ),
    ]
