# Generated by Django 6.0.6 on 2026-08-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.BigAutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='nombres', max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(db_column='apellidos', max_length=100, verbose_name='Apellidos')),
                ('identificacion', models.CharField(db_column='identificacion', max_length=20, unique=True, verbose_name='Identificacion')),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=15, null=True, verbose_name='Telefono convencional')),
                ('celular', models.CharField(db_column='celular', max_length=15, verbose_name='Celular')),
                ('correo', models.EmailField(db_column='correo', max_length=254, unique=True, verbose_name='Correo electronico')),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=200, null=True, verbose_name='Direccion')),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('separado', 'Separado/a'), ('union libre', 'Union libre')], db_column='estado_civil', default='soltero', max_length=20, verbose_name='Estado civil')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], db_column='estado', default='activo', max_length=10, verbose_name='Estado de la cuenta')),
                ('fecha_registro', models.DateField(auto_now_add=True, db_column='fecha_registro', verbose_name='Fecha de registro')),
                ('rol', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin Facultad'), ('USER', 'Usuario')], db_column='rol', default='USER', max_length=15, verbose_name='Rol del sistema')),
                ('is_active', models.BooleanField(db_column='activo', default=True, verbose_name='Puede iniciar sesion')),
                ('is_staff', models.BooleanField(db_column='es_staff', default=False, verbose_name='Acceso al panel de administracion')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
