# Generated by Django 6.0.6 on 2026-08-11 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='facultad',
            field=models.ForeignKey(blank=True, db_column='id_facultad', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='cursos.facultad', verbose_name='Facultad a la que pertenece'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
