# Generated by Django 6.0.6 on 2026-08-11 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.BigAutoField(db_column='id_facultad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=200, unique=True, verbose_name='Nombre de la facultad')),
                ('codigo', models.CharField(db_column='codigo', max_length=10, unique=True, verbose_name='Codigo')),
                ('admin', models.ForeignKey(blank=True, db_column='id_admin', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facultades_administradas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador de la facultad')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'db_table': 'facultad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.BigAutoField(db_column='id_curso', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=200, verbose_name='Nombre del curso')),
                ('codigo', models.CharField(db_column='codigo', max_length=20, unique=True, verbose_name='Codigo del curso')),
                ('descripcion', models.TextField(db_column='descripcion', verbose_name='Descripcion')),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(db_column='fecha_fin', verbose_name='Fecha de finalizacion')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('archivado', 'Archivado')], db_column='estado', default='activo', max_length=10, verbose_name='Estado del curso')),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.PROTECT, related_name='cursos_como_profesor', to=settings.AUTH_USER_MODEL, verbose_name='Profesor responsable')),
                ('facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='cursos.facultad', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'ordering': ['-fecha_inicio', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='FormulaComponente',
            fields=[
                ('id_componente', models.BigAutoField(db_column='id_componente', primary_key=True, serialize=False)),
                ('componente', models.CharField(db_column='componente', max_length=100, verbose_name='Nombre del componente')),
                ('porcentaje', models.PositiveSmallIntegerField(db_column='porcentaje', verbose_name='Porcentaje')),
                ('orden', models.PositiveSmallIntegerField(db_column='orden', default=0, verbose_name='Orden')),
                ('curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, related_name='formula', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Componente de formula',
                'verbose_name_plural': 'Componentes de formula',
                'db_table': 'formula_componente',
                'ordering': ['curso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.BigAutoField(db_column='id_inscripcion', primary_key=True, serialize=False)),
                ('rol_en_curso', models.CharField(choices=[('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante')], db_column='rol_en_curso', default='ESTUDIANTE', max_length=15, verbose_name='Rol en el curso')),
                ('fecha', models.DateField(auto_now_add=True, db_column='fecha', verbose_name='Fecha de inscripcion')),
                ('curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='cursos.curso', verbose_name='Curso')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripcion',
                'ordering': ['curso', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.BigAutoField(db_column='id_modulo', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=200, verbose_name='Titulo del modulo')),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True, verbose_name='Descripcion')),
                ('orden', models.PositiveSmallIntegerField(db_column='orden', default=1, verbose_name='Orden')),
                ('curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, related_name='modulos', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'db_table': 'modulo',
                'ordering': ['curso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.BigAutoField(db_column='id_material', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('enlace', 'Enlace externo')], db_column='tipo', default='video', max_length=10, verbose_name='Tipo de material')),
                ('titulo', models.CharField(db_column='titulo', max_length=200, verbose_name='Titulo del material')),
                ('url', models.URLField(db_column='url', verbose_name='Enlace del recurso')),
                ('modulo', models.ForeignKey(db_column='id_modulo', on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='cursos.modulo', verbose_name='Modulo')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'material',
                'ordering': ['modulo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoModulo',
            fields=[
                ('id_progreso', models.BigAutoField(db_column='id_progreso', primary_key=True, serialize=False)),
                ('completado', models.BooleanField(db_column='completado', default=False, verbose_name='Modulo completado')),
                ('fecha', models.DateField(auto_now=True, db_column='fecha', verbose_name='Ultima actualizacion')),
                ('modulo', models.ForeignKey(db_column='id_modulo', on_delete=django.db.models.deletion.PROTECT, related_name='progresos', to='cursos.modulo', verbose_name='Modulo')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='progresos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Progreso de modulo',
                'verbose_name_plural': 'Progresos de modulo',
                'db_table': 'progreso_modulo',
                'ordering': ['usuario', 'modulo'],
            },
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='ck_curso_fechas_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='formulacomponente',
            constraint=models.UniqueConstraint(fields=('curso', 'componente'), name='uq_formula_curso_componente'),
        ),
        migrations.AddConstraint(
            model_name='formulacomponente',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje__gte', 1), ('porcentaje__lte', 100)), name='ck_formula_porcentaje_valido'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('usuario', 'curso'), name='uq_inscripcion_usuario_curso'),
        ),
        migrations.AddConstraint(
            model_name='modulo',
            constraint=models.UniqueConstraint(fields=('curso', 'orden'), name='uq_modulo_curso_orden'),
        ),
        migrations.AddConstraint(
            model_name='modulo',
            constraint=models.CheckConstraint(condition=models.Q(('orden__gte', 1)), name='ck_modulo_orden_positivo'),
        ),
        migrations.AddConstraint(
            model_name='progresomodulo',
            constraint=models.UniqueConstraint(fields=('usuario', 'modulo'), name='uq_progreso_usuario_modulo'),
        ),
    ]
