# Generated by Django 6.0.6 on 2026-08-11 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id_quiz', models.BigAutoField(db_column='id_quiz', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=200, verbose_name='Titulo del quiz')),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True, verbose_name='Descripcion')),
                ('tiempo_limite_min', models.PositiveSmallIntegerField(blank=True, db_column='tiempo_limite_min', null=True, verbose_name='Tiempo limite en minutos')),
                ('fecha_limite', models.DateTimeField(db_column='fecha_limite', verbose_name='Fecha limite')),
                ('curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quiz',
                'ordering': ['fecha_limite', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.BigAutoField(db_column='id_pregunta', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('opcion_multiple_una', 'Opcion multiple (1 respuesta)'), ('opcion_multiple_varias', 'Opcion multiple (varias respuestas)'), ('verdadero_falso', 'Verdadero / Falso'), ('completar_espacios', 'Completar espacios'), ('relacionar_columnas', 'Relacionar columnas'), ('ordenamiento', 'Ordenamiento'), ('respuesta_numerica', 'Respuesta numerica'), ('menu_desplegable', 'Menu desplegable'), ('seleccion_imagen', 'Seleccion en imagen'), ('respuesta_corta', 'Respuesta corta'), ('ensayo', 'Ensayo'), ('subida_archivo', 'Subida de archivo'), ('respuesta_imagen', 'Respuesta con imagen'), ('editor_codigo', 'Editor de codigo'), ('escala_valoracion', 'Escala de valoracion')], db_column='tipo', default='opcion_multiple_una', max_length=30, verbose_name='Tipo de pregunta')),
                ('enunciado', models.TextField(db_column='enunciado', verbose_name='Enunciado')),
                ('puntaje', models.DecimalField(db_column='puntaje', decimal_places=2, default=1, max_digits=10, verbose_name='Puntaje')),
                ('orden', models.PositiveSmallIntegerField(db_column='orden', default=0, verbose_name='Orden')),
                ('opciones', models.JSONField(blank=True, db_column='opciones', default=list, verbose_name='Opciones de respuesta')),
                ('respuesta_correcta', models.JSONField(blank=True, db_column='respuesta_correcta', null=True, verbose_name='Respuesta correcta')),
                ('quiz', models.ForeignKey(db_column='id_quiz', on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='evaluaciones.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'pregunta',
                'ordering': ['quiz', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaQuiz',
            fields=[
                ('id_respuesta_quiz', models.BigAutoField(db_column='id_respuesta_quiz', primary_key=True, serialize=False)),
                ('respuestas', models.JSONField(blank=True, db_column='respuestas', default=dict, verbose_name='Respuestas enviadas')),
                ('nota_automatica', models.DecimalField(db_column='nota_automatica', decimal_places=2, default=0, max_digits=10, verbose_name='Nota automatica')),
                ('nota_manual', models.DecimalField(blank=True, db_column='nota_manual', decimal_places=2, max_digits=10, null=True, verbose_name='Nota manual')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha', verbose_name='Fecha de envio')),
                ('quiz', models.ForeignKey(db_column='id_quiz', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='evaluaciones.quiz', verbose_name='Quiz')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_quiz', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Respuesta de quiz',
                'verbose_name_plural': 'Respuestas de quiz',
                'db_table': 'respuesta_quiz',
                'ordering': ['quiz', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.BigAutoField(db_column='id_tarea', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=200, verbose_name='Titulo de la tarea')),
                ('descripcion', models.TextField(db_column='descripcion', verbose_name='Descripcion')),
                ('criterios', models.TextField(blank=True, db_column='criterios', null=True, verbose_name='Criterios de calificacion')),
                ('fecha_limite', models.DateTimeField(db_column='fecha_limite', verbose_name='Fecha limite de entrega')),
                ('puntaje_maximo', models.DecimalField(db_column='puntaje_maximo', decimal_places=2, default=10, max_digits=10, verbose_name='Puntaje maximo')),
                ('curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tarea',
                'ordering': ['fecha_limite', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.BigAutoField(db_column='id_entrega', primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado')], db_column='estado', default='pendiente', max_length=15, verbose_name='Estado de la entrega')),
                ('fecha', models.DateTimeField(blank=True, db_column='fecha', null=True, verbose_name='Fecha de entrega')),
                ('texto', models.TextField(blank=True, db_column='texto', null=True, verbose_name='Respuesta escrita')),
                ('archivo', models.CharField(blank=True, db_column='archivo', max_length=300, null=True, verbose_name='Archivo entregado')),
                ('imagen', models.URLField(blank=True, db_column='imagen', null=True, verbose_name='Imagen entregada')),
                ('link', models.URLField(blank=True, db_column='link', null=True, verbose_name='Enlace entregado')),
                ('nota', models.DecimalField(blank=True, db_column='nota', decimal_places=2, max_digits=10, null=True, verbose_name='Nota obtenida')),
                ('comentario', models.TextField(blank=True, db_column='comentario', null=True, verbose_name='Comentario del profesor')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('tarea', models.ForeignKey(db_column='id_tarea', on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='evaluaciones.tarea', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entrega',
                'ordering': ['tarea', 'usuario'],
            },
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('curso', 'titulo'), name='uq_quiz_curso_titulo'),
        ),
        migrations.AddConstraint(
            model_name='pregunta',
            constraint=models.CheckConstraint(condition=models.Q(('puntaje__gte', 0)), name='ck_pregunta_puntaje_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='respuestaquiz',
            constraint=models.UniqueConstraint(fields=('quiz', 'usuario'), name='uq_respuesta_quiz_usuario'),
        ),
        migrations.AddConstraint(
            model_name='respuestaquiz',
            constraint=models.CheckConstraint(condition=models.Q(('nota_automatica__gte', 0)), name='ck_respuesta_quiz_nota_auto_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='respuestaquiz',
            constraint=models.CheckConstraint(condition=models.Q(('nota_manual__isnull', True), ('nota_manual__gte', 0), _connector='OR'), name='ck_respuesta_quiz_nota_manual_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('curso', 'titulo'), name='uq_tarea_curso_titulo'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(('puntaje_maximo__gte', 0)), name='ck_tarea_puntaje_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='entrega',
            constraint=models.UniqueConstraint(fields=('tarea', 'usuario'), name='uq_entrega_tarea_usuario'),
        ),
        migrations.AddConstraint(
            model_name='entrega',
            constraint=models.CheckConstraint(condition=models.Q(('nota__isnull', True), ('nota__gte', 0), _connector='OR'), name='ck_entrega_nota_no_negativa'),
        ),
    ]
